version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "todo_db"]
      interval: 5s
      retries: 5
      timeout: 3s

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/todo_db
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && uvicorn backend.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data:
